name: Publish website
on:
  push:
    branches:
      - main
  workflow_dispatch: 
permissions:
  contents: write
  pages: write  

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clone the repository
        run: git clone https://github.com/mozilla/pdf.js.git

      - name: Copy static to pdf.js
        run: cp -r static pdf.js/

      - name: Change web/app.js
        working-directory: pdf.js
        run: sed -z 's/if (fileOrigin !== viewerOrigin) {\n *throw new Error("file origin does not match viewer.s");\n *}//g' web/app.js

      - name: Install dependencies
        working-directory: pdf.js
        run: npm ci
        
      - name: Build the website
        working-directory: pdf.js
        run: npx gulp web

      - name: Archive the website
        working-directory: pdf.js
        shell: sh
        run: |
          chmod -c -R +rX "$INPUT_PATH" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
          mkdir "$INPUT_PATH/static"
          cp -r static/*  "$INPUT_PATH/static"
          tar \
            --dereference --hard-dereference \
            --directory "$INPUT_PATH" \
            -cvf "$RUNNER_TEMP/website.tar" \
            --exclude=.git \
            --exclude=.github \
            .
        env:
          INPUT_PATH: build/gh-pages

      - name: Upload the website
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{ runner.temp }}/website.tar
          retention-days: 1
          if-no-files-found: error

      - name: Copy build files to website directory
        working-directory: pdf.js
        run:  |
           mkdir website
           cp -r build/gh-pages/* website/
        
      # - name: Rename and Replace Extension
      #   run: |
      #     files_to_rename=("pdf.mjs" "pdf.sandbox.mjs" "pdf.worker.mjs")
      #     for file in "${files_to_rename[@]}"; do
      #       if [ -f "website/build/$file" ]; then
      #         mv "website/build/$file" "website/build/${file%.mjs}.js"
      #         sed -i 's/\.mjs/\.js/g' "website/build/${file%.mjs}.js"
      #       else
      #         echo "File not found: $file"
      #       fi
      #     done
      #     if [ -f "website/web/viewer.mjs" ]; then
      #         mv "website/web/viewer.mjs" "website/web/viewer.js"
      #         sed -i 's/\.mjs/\.js/g' "website/web/viewer.js"
      #     else
      #         echo "File not found: viewer.html"
      #     fi
      #     if [ -f "website/web/viewer.html" ]; then
      #         sed -i 's/\.mjs/\.js/g' "website/web/viewer.html"
      #     else
      #         echo "File not found: viewer.html"
      #     fi
        
      - name: Add, commit, and push to current branch
        working-directory: pdf.js/website
        run: |
          git init
          git remote set-url origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/wzcv/pdf.js_web.git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b website
          git add .
          # git add website
          # git add -f website/build/* 
          git commit -m "Add website directory with build files" || echo "No changes to commit"
          git push -u origin website || echo "Push failed"

        env:
          GIT_PUSH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-and-deploy
    permissions:
      pages: write  # Required to deploy to GitHub Pages.
      id-token: write  # Required to verify that the deployment originates from this workflow.

    steps:
      - name: Deploy the website
        uses: actions/deploy-pages@v4
